### ISSUE TITLE
通过volo-build生成的rs中无相关的结构体

### ISSUE THREAD

**Issue by brian-god** [cloudwego/volo#382]
通过定义的proto文件生成的文件

当proto中定义有service生成的volo_gen.rs有内容
把proto中的service注释掉生成的volo_gen.rs就为下方图片所示的内容了

因为定义的有些message只想在序列化的时候使用，并不会做rpc的方法参数或返回值，这样的message无法生成

![1709894392225](https://github.com/cloudwego/volo/assets/38514444/9cc06607-a7f2-4cc7-bfa1-4a56a520c8f6)

![1709894446668](https://github.com/cloudwego/volo/assets/38514444/8bb49f53-b461-4064-85d9-acb45993d9b1)
![1709894475942](https://github.com/cloudwego/volo/assets/38514444/404b4688-1fce-42ec-bdf0-da5115d0ec39)

**Comment by Millione** [comment]
可以在 volo.yml 中通过 touch 字段来强制生成需要的 message 结构体或者通过指定 touch_all 字段为 true 来强制生成所有结构体：
```yml
entries:
  proto:
    touch_all: true
    idls:
      - source: local
        touch: [PushReq, PushReply]
```
FYI: 在生成代码的过程中，默认会进行剪枝生成（也就是只生成 service 入口处参数所依赖到的结构体），这样可以大幅减小生成代码的体积以及加快 Rust Analyzer 索引的速度。
