### ISSUE TITLE
idl repo includes path 有问题

### ISSUE THREAD

**Issue by hohowt** [cloudwego/volo#462]
## Bug Report
includes path错误
如果是目录，无法import。
如果是文件，则路径有问题
`googleapis/googleapis/google/api/http.proto/google/api/http.proto`
<img width="2287" alt="图片" src="https://github.com/cloudwego/volo/assets/56286666/266dd523-71b4-4470-bc2a-8e131cc972b3">
<img width="2044" alt="图片" src="https://github.com/cloudwego/volo/assets/56286666/9330fa83-510d-474b-bbbd-cf9459f104e6">

### Version
最新版

### Platform
mac

### Crates
```toml
volo-gen = { path = "./volo-gen" }
volo.workspace = true
volo-grpc.workspace = true
pilota.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
```
### Description

I tried this code:

<code sample that causes the bug>

I expected to see this happen: <explanation>

Instead, this happened: <explanation>
-->
