### ISSUE TITLE
Rust identifiers aren't being sanitized

### ISSUE THREAD

**Issue by NickLarsenNZ** [cloudwego/volo#495]
### Version

```
❯ cargo tree | grep volo
├── volo v0.10.3
└── volo-thrift v0.10.4
    └── volo v0.10.3 (*)
└── volo-build v0.10.14
    ├── volo v0.10.3 (*)
```

### Platform

```
❯ uname -a
Linux workdogg 6.8.12 #1-NixOS SMP PREEMPT_DYNAMIC Thu May 30 07:49:53 UTC 2024 x86_64 GNU/Linux
```

### Description

I tried:

volo.yaml

```yml
---
entries:
  thrift:
    filename: thrift_gen.rs
    protocol: thrift
    repos:
    services:
      - idl:
          source: local
          # https://github.com/apache/hive/blob/0b4ee968b2488796fb0120c4f20a2a4d4ac37799/standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
          path: thrift/hive_metastore.thrift
      - idl:
          source: local
          # https://github.com/apache/thrift/blob/bcc9cee244a282d9a716890c50ab95a9bb677e80/contrib/fb303/if/fb303.thrift
          path: thrift/share/fb303/if/fb303.thrift
```

build.rs:

```rust
fn main() {
    volo_build::ConfigBuilder::default()
        .write()
        .expect("successful generation");
}

```

Error output:

```
  error: expected identifier, found keyword `type`
        --> /home/nick/dev/github.com/NickLarsenNZ/dummy/target/debug/build/jive-metastore-d0f400dcf02a9bb6/out/thrift_gen.rs:254376:49
         |
  254376 |                 match self.inner.drop_type(args.type).await {
         |                                                 ^^^^ expected identifier, found keyword
         |
  help: escape `type` to use it as an identifier
         |
  254376 |                 match self.inner.drop_type(args.r#type).await {
         |                                                 ++
```

The Rust keywords either need to be renamed, eg: `type -> ty`, or become literals, eg: `r#type`.
